from app.crud.crud_persona import persona
from app.crud.crud_usuario import usuario
from app.crud.crud_rol import rol
from app.crud.crud_rol_usuario import rol_usuario
from app.crud.crud_dispositivo_usuario import dispositivo_usuario
from app.crud.crud_sesion import sesion
from app.crud.crud_vehiculo import vehiculo
from app.crud.crud_rol_permiso import rol_permiso
from app.crud.crud_permiso import permiso
from app.crud.crud_solicitud_afiliacion import solicitud_afiliacion
from app.crud.crud_taller import taller
from app.crud.crud_solicitud_diagnostico import solicitud_diagnostico
from app.crud.crud_evidencia import evidencia 
from app.crud.crud_diagnostico import diagnostico
from app.crud.crud_tipo_incidente import tipo_incidente
from app.crud.crud_incidente import incidente 
from app.crud.crud_categoria_incidente import categoria_incidente
from app.crud.crud_configuracion_sistema import configuracion_sistema
from app.crud.crud_solicitud_servicio import solicitud_servicio
from app.crud.crud_servicio import servicio
from app.crud.crud_servicio_tecnico import servicio_tecnico
from app.crud.crud_servicio_vehiculo import servicio_vehiculo
from app.crud.crud_empleado import empleado
