"""add_empleado_ubicacion_table

Revision ID: 0d77f7024a05
Revises: 8d27e4211689
Create Date: 2026-04-26 16:52:34.431362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d77f7024a05'
down_revision: Union[str, Sequence[str], None] = '8d27e4211689'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empleado_ubicacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_empleado', sa.Integer(), nullable=False),
    sa.Column('latitud', sa.DECIMAL(precision=10, scale=8), nullable=False),
    sa.Column('longitud', sa.DECIMAL(precision=11, scale=8), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('id_servicio', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_empleado'], ['empleado.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicio.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empleado_ubicacion_id'), 'empleado_ubicacion', ['id'], unique=False)
    # Índices adicionales para performance
    op.create_index('idx_empleado_ubicacion_empleado_activa', 'empleado_ubicacion', ['id_empleado', 'activa'], unique=False)
    op.create_index('idx_empleado_ubicacion_servicio', 'empleado_ubicacion', ['id_servicio'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_empleado_ubicacion_servicio', table_name='empleado_ubicacion')
    op.drop_index('idx_empleado_ubicacion_empleado_activa', table_name='empleado_ubicacion')
    op.drop_index(op.f('ix_empleado_ubicacion_id'), table_name='empleado_ubicacion')
    op.drop_table('empleado_ubicacion')
    # ### end Alembic commands ###
