"""nombre_de_la_migracion

Revision ID: 75d50c36d769
Revises: 0d77f7024a05
Create Date: 2026-04-26 18:52:32.419689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75d50c36d769'
down_revision: Union[str, Sequence[str], None] = '0d77f7024a05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('valoracion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('puntos', sa.SmallInteger(), nullable=False),
    sa.Column('id_servicio', sa.Integer(), nullable=False),
    sa.CheckConstraint('puntos >= 1 AND puntos <= 5', name='check_puntos_valoracion'),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicio.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_servicio')
    )
    op.create_index(op.f('ix_valoracion_id'), 'valoracion', ['id'], unique=False)
    op.drop_index(op.f('idx_empleado_ubicacion_empleado_activa'), table_name='empleado_ubicacion')
    op.drop_index(op.f('idx_empleado_ubicacion_servicio'), table_name='empleado_ubicacion')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_empleado_ubicacion_servicio'), 'empleado_ubicacion', ['id_servicio'], unique=False)
    op.create_index(op.f('idx_empleado_ubicacion_empleado_activa'), 'empleado_ubicacion', ['id_empleado', 'activa'], unique=False)
    op.drop_index(op.f('ix_valoracion_id'), table_name='valoracion')
    op.drop_table('valoracion')
    # ### end Alembic commands ###
