"""añadir tabla de solicitud_servicio

Revision ID: 7ad5ca26661a
Revises: e3a8b12c6d45
Create Date: 2026-04-25 00:31:13.489720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '7ad5ca26661a'
down_revision: Union[str, Sequence[str], None] = 'e3a8b12c6d45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitud_servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ubicacion', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('fecha', sa.TIMESTAMP(), nullable=False, server_default=sa.text('NOW()')),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'aceptada', 'rechazada', 'cancelada', 'expirada', name='estadosolicitudservicio'), nullable=False, server_default='pendiente'),
    sa.Column('fecha_aceptada', sa.TIMESTAMP(), nullable=True),
    sa.Column('costo_estimado', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('sugerido_por', sa.Enum('ia', 'conductor', name='sugeridoportipo'), nullable=False),
    sa.Column('id_taller', sa.Integer(), nullable=False),
    sa.Column('id_diagnostico', sa.Integer(), nullable=False),
    sa.CheckConstraint('costo_estimado >= 0', name='check_costo_estimado_positivo'),
    sa.ForeignKeyConstraint(['id_diagnostico'], ['diagnostico.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_taller'], ['taller.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_taller', 'id_diagnostico', name='uq_solicitud_taller_diagnostico')
    )
    op.create_index(op.f('ix_solicitud_servicio_id'), 'solicitud_servicio', ['id'], unique=False)
    op.create_index('ix_solicitud_servicio_taller', 'solicitud_servicio', ['id_taller'], unique=False)
    op.create_index('ix_solicitud_servicio_diagnostico', 'solicitud_servicio', ['id_diagnostico'], unique=False)
    op.create_index('ix_solicitud_servicio_estado', 'solicitud_servicio', ['estado'], unique=False)
    op.create_index('ix_solicitud_servicio_fecha', 'solicitud_servicio', [sa.text('fecha DESC')], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Eliminar índices
    op.drop_index('ix_solicitud_servicio_fecha', table_name='solicitud_servicio')
    op.drop_index('ix_solicitud_servicio_estado', table_name='solicitud_servicio')
    op.drop_index('ix_solicitud_servicio_diagnostico', table_name='solicitud_servicio')
    op.drop_index('ix_solicitud_servicio_taller', table_name='solicitud_servicio')
    op.drop_index(op.f('ix_solicitud_servicio_id'), table_name='solicitud_servicio')
    
    # Eliminar tabla
    op.drop_table('solicitud_servicio')
    
    # Eliminar tipos ENUM (solo si no son usados por otras tablas)
    # Nota: Comentado por seguridad, descomentar si estás seguro
    # op.execute('DROP TYPE IF EXISTS estadosolicitudservicio')
    # op.execute('DROP TYPE IF EXISTS sugeridoportipo')
    # ### end Alembic commands ###
