"""mensaje descriptivo

Revision ID: 8d27e4211689
Revises: abc123update
Create Date: 2026-04-26 09:51:55.859362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '8d27e4211689'
down_revision: Union[str, Sequence[str], None] = 'abc123update'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Usar el ENUM existente en lugar de crear uno nuevo
    estadoservicio_enum = postgresql.ENUM(
        'creado', 'tecnico_asignado', 'en_camino', 'en_lugar', 
        'en_atencion', 'finalizado', 'cancelado', 
        name='estadoservicio',
        create_type=False  # No crear el tipo, usar el existente
    )
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial_estados_servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estado', estadoservicio_enum, nullable=False),
    sa.Column('tiempo', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id_servicio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicio.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_estados_servicio_id'), 'historial_estados_servicio', ['id'], unique=False)
    op.create_table('metrica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tiempo_respuesta', sa.Interval(), nullable=True),
    sa.Column('tiempo_llegada', sa.Interval(), nullable=True),
    sa.Column('tiempo_resolucion', sa.Interval(), nullable=True),
    sa.Column('id_servicio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicio.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_servicio')
    )
    op.create_index(op.f('ix_metrica_id'), 'metrica', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metrica_id'), table_name='metrica')
    op.drop_table('metrica')
    op.drop_index(op.f('ix_historial_estados_servicio_id'), table_name='historial_estados_servicio')
    op.drop_table('historial_estados_servicio')
    # ### end Alembic commands ###
