"""add quote tables

Revision ID: add_quote_tables
Revises: simplify_empleado_estado
Create Date: 2026-06-06 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'add_quote_tables'
down_revision: Union[str, Sequence[str], None] = 'simplify_empleado_estado'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Crear enum para estado de solicitud de cotización (si no existe)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE estadoquoterequest AS ENUM ('pendiente', 'con_respuesta', 'aceptada', 'rechazada', 'expirada');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$
    """)
    
    # Crear enum para estado de respuesta de cotización (si no existe)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE estadoquoteresponse AS ENUM ('pendiente', 'respondida', 'rechazada', 'expirada');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$
    """)
    
    # Crear tabla quote_request con VARCHAR en lugar de ENUM para evitar conflicto
    op.create_table('quote_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ubicacion', sa.String(), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_expiracion', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('fecha_aceptada', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id_vehiculo', sa.Integer(), nullable=False),
    sa.Column('id_servicio', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['usuario.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_servicio'], ['servicio.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_vehiculo'], ['vehiculo.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_request_id'), 'quote_request', ['id'], unique=False)
    op.create_index('idx_quote_request_cliente', 'quote_request', ['id_cliente'], unique=False)
    op.create_index('idx_quote_request_estado', 'quote_request', ['estado'], unique=False)
    op.create_index('idx_quote_request_fecha_creacion', 'quote_request', ['fecha_creacion'], unique=False)
    
    # Crear tabla quote_response con VARCHAR en lugar de ENUM
    op.create_table('quote_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_respuesta', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id_quote_request', sa.Integer(), nullable=False),
    sa.Column('id_taller', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_quote_request'], ['quote_request.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_taller'], ['taller.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_response_id'), 'quote_response', ['id'], unique=False)
    op.create_index('idx_quote_response_taller', 'quote_response', ['id_taller'], unique=False)
    op.create_index('idx_quote_response_request', 'quote_response', ['id_quote_request'], unique=False)
    op.create_index('idx_quote_response_estado', 'quote_response', ['estado'], unique=False)
    
    # Crear tabla quote_item
    op.create_table('quote_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id_quote_response', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_quote_response'], ['quote_response.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_item_id'), 'quote_item', ['id'], unique=False)
    op.create_index('idx_quote_item_response', 'quote_item', ['id_quote_response'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_quote_item_response', table_name='quote_item')
    op.drop_index(op.f('ix_quote_item_id'), table_name='quote_item')
    op.drop_table('quote_item')
    
    op.drop_index('idx_quote_response_estado', table_name='quote_response')
    op.drop_index('idx_quote_response_request', table_name='quote_response')
    op.drop_index('idx_quote_response_taller', table_name='quote_response')
    op.drop_index(op.f('ix_quote_response_id'), table_name='quote_response')
    op.drop_table('quote_response')
    
    op.drop_index('idx_quote_request_fecha_creacion', table_name='quote_request')
    op.drop_index('idx_quote_request_estado', table_name='quote_request')
    op.drop_index('idx_quote_request_cliente', table_name='quote_request')
    op.drop_index(op.f('ix_quote_request_id'), table_name='quote_request')
    op.drop_table('quote_request')
    
    op.execute("DROP TYPE estadoquoteresponse")
    op.execute("DROP TYPE estadoquoterequest")
    # ### end Alembic commands ###
