"""initial_migration

Revision ID: c2484a04b923
Revises: 
Create Date: 2026-04-22 10:12:13.535545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'c2484a04b923'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria_incidente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_categoria_incidente_id'), 'categoria_incidente', ['id'], unique=False)
    op.create_table('especialidad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_especialidad_id'), 'especialidad', ['id'], unique=False)
    op.create_table('permiso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concepto', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('concepto')
    )
    op.create_index(op.f('ix_permiso_id'), 'permiso', ['id'], unique=False)
    op.create_table('persona',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('apellido_p', sa.String(length=100), nullable=True),
    sa.Column('apellido_m', sa.String(length=100), nullable=True),
    sa.Column('ci', sa.String(length=10), nullable=True),
    sa.Column('complemento', sa.String(length=2), nullable=True),
    sa.Column('telefono', sa.String(length=15), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_persona_id'), 'persona', ['id'], unique=False)
    op.create_table('rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_rol_id'), 'rol', ['id'], unique=False)
    op.create_table('dispositivo_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_fcm', sa.Text(), nullable=False),
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispositivo_usuario_id'), 'dispositivo_usuario', ['id'], unique=False)
    op.create_table('rol_permiso',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('id_permiso', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_permiso'], ['permiso.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_rol'], ['rol.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_rol', 'id_permiso')
    )
    op.create_table('sesion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('fecha_inicio', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_expira', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_sesion_id'), 'sesion', ['id'], unique=False)
    op.create_table('tipo_incidente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concepto', sa.String(length=150), nullable=False),
    sa.Column('prioridad', sa.SmallInteger(), nullable=False),
    sa.Column('requiere_remolque', sa.Boolean(), nullable=False),
    sa.Column('id_categoria_incidente', sa.Integer(), nullable=True),
    sa.CheckConstraint('prioridad BETWEEN 1 AND 5', name='check_prioridad_tipo_incidente'),
    sa.ForeignKeyConstraint(['id_categoria_incidente'], ['categoria_incidente.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('concepto')
    )
    op.create_index(op.f('ix_tipo_incidente_id'), 'tipo_incidente', ['id'], unique=False)
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('contrasena', sa.String(length=255), nullable=False),
    sa.Column('url_img_perfil', sa.Text(), nullable=True),
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_persona'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_usuario_id'), 'usuario', ['id'], unique=False)
    op.create_table('vehiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('anio', sa.SmallInteger(), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('tipo', sa.Enum('auto', 'camioneta', 'moto', 'camion', 'microbus', 'otro', name='tipovehiculo'), nullable=False),
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.CheckConstraint('anio >= 1900 AND anio <= 2100', name='check_anio'),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula')
    )
    op.create_index(op.f('ix_vehiculo_id'), 'vehiculo', ['id'], unique=False)
    op.create_table('solicitud_afiliacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('ubicacion', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('fecha', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_revision', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'aprobada', 'rechazada', name='estadosolicitudafiliacion'), nullable=False),
    sa.Column('comentario_revision', sa.Text(), nullable=True),
    sa.Column('id_usuario_solicita', sa.Integer(), nullable=False),
    sa.Column('id_usuario_revisa', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario_revisa'], ['usuario.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_usuario_solicita'], ['usuario.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitud_afiliacion_id'), 'solicitud_afiliacion', ['id'], unique=False)
    op.create_table('solicitud_diagnostico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'diagnosticada', 'cancelada', 'error', name='estadosolicituddiagnostico'), nullable=False),
    sa.Column('ubicacion', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('id_persona', sa.Integer(), nullable=False),
    sa.Column('id_vehiculo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_vehiculo'], ['vehiculo.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitud_diagnostico_id'), 'solicitud_diagnostico', ['id'], unique=False)
    op.create_table('diagnostico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('nivel_confianza', sa.DECIMAL(precision=5, scale=4), nullable=False),
    sa.Column('fecha', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id_solicitud_diagnostico', sa.Integer(), nullable=False),
    sa.CheckConstraint('nivel_confianza >= 0 AND nivel_confianza <= 1', name='check_nivel_confianza_diagnostico'),
    sa.ForeignKeyConstraint(['id_solicitud_diagnostico'], ['solicitud_diagnostico.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_solicitud_diagnostico')
    )
    op.create_index(op.f('ix_diagnostico_id'), 'diagnostico', ['id'], unique=False)
    op.create_table('evidencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('transcripcion', sa.Text(), nullable=True),
    sa.Column('tipo', sa.Enum('audio', 'imagen', name='tipoevidencia'), nullable=False),
    sa.Column('id_solicitud_diagnostico', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_solicitud_diagnostico'], ['solicitud_diagnostico.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidencia_id'), 'evidencia', ['id'], unique=False)
    op.create_table('taller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('ubicacion', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_fin', sa.Time(), nullable=True),
    sa.Column('url_web', sa.Text(), nullable=True),
    sa.Column('puntos', sa.DECIMAL(precision=3, scale=2), nullable=False),
    sa.Column('estado', sa.Enum('activo', 'suspendido', name='estadotaller'), nullable=False),
    sa.Column('id_solicitud_afiliacion', sa.Integer(), nullable=False),
    sa.CheckConstraint('hora_fin > hora_inicio', name='check_horario'),
    sa.CheckConstraint('puntos >= 0 AND puntos <= 5', name='check_puntos'),
    sa.ForeignKeyConstraint(['id_solicitud_afiliacion'], ['solicitud_afiliacion.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_solicitud_afiliacion'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_taller_id'), 'taller', ['id'], unique=False)
    op.create_table('empleado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_ingreso', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_salida', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('estado', sa.Enum('activo', 'disponible', 'en_servicio', 'suspendido', name='estadoempleado'), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_taller', sa.Integer(), nullable=False),
    sa.CheckConstraint('fecha_salida IS NULL OR fecha_salida >= fecha_ingreso', name='chk_fechas_empleado'),
    sa.ForeignKeyConstraint(['id_taller'], ['taller.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empleado_id'), 'empleado', ['id'], unique=False)
    op.create_table('incidente',
    sa.Column('id_diagnostico', sa.Integer(), nullable=False),
    sa.Column('id_tipo_incidente', sa.Integer(), nullable=False),
    sa.Column('sugerido_por', sa.Enum('ia', 'conductor', name='sugeridopor'), nullable=False),
    sa.Column('nivel_confianza', sa.DECIMAL(precision=5, scale=4), nullable=False),
    sa.CheckConstraint('nivel_confianza >= 0 AND nivel_confianza <= 1', name='check_nivel_confianza_incidente'),
    sa.ForeignKeyConstraint(['id_diagnostico'], ['diagnostico.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_tipo_incidente'], ['tipo_incidente.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_diagnostico', 'id_tipo_incidente')
    )
    op.create_table('rol_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('id_taller', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_rol'], ['rol.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_taller'], ['taller.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rol_usuario_id'), 'rol_usuario', ['id'], unique=False)
    op.create_table('vehiculo_taller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('anio', sa.SmallInteger(), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('tipo', sa.Enum('servicio', 'remolque', 'otro', name='tipovehiculotaller'), nullable=False),
    sa.Column('estado', sa.Enum('disponible', 'en_servicio', 'en_mantenimiento', 'inactivo', name='estadovehiculotaller'), nullable=False),
    sa.Column('id_taller', sa.Integer(), nullable=False),
    sa.CheckConstraint('anio >= 1900 AND anio <= 2100', name='check_anio_vehiculo_taller'),
    sa.ForeignKeyConstraint(['id_taller'], ['taller.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula')
    )
    op.create_index(op.f('ix_vehiculo_taller_id'), 'vehiculo_taller', ['id'], unique=False)
    op.create_table('tecnico_especialidad',
    sa.Column('id_empleado', sa.Integer(), nullable=False),
    sa.Column('id_especialidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_empleado'], ['empleado.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_especialidad'], ['especialidad.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_empleado', 'id_especialidad')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tecnico_especialidad')
    op.drop_index(op.f('ix_vehiculo_taller_id'), table_name='vehiculo_taller')
    op.drop_table('vehiculo_taller')
    op.drop_index(op.f('ix_rol_usuario_id'), table_name='rol_usuario')
    op.drop_table('rol_usuario')
    op.drop_table('incidente')
    op.drop_index(op.f('ix_empleado_id'), table_name='empleado')
    op.drop_table('empleado')
    op.drop_index(op.f('ix_taller_id'), table_name='taller')
    op.drop_table('taller')
    op.drop_index(op.f('ix_evidencia_id'), table_name='evidencia')
    op.drop_table('evidencia')
    op.drop_index(op.f('ix_diagnostico_id'), table_name='diagnostico')
    op.drop_table('diagnostico')
    op.drop_index(op.f('ix_solicitud_diagnostico_id'), table_name='solicitud_diagnostico')
    op.drop_table('solicitud_diagnostico')
    op.drop_index(op.f('ix_solicitud_afiliacion_id'), table_name='solicitud_afiliacion')
    op.drop_table('solicitud_afiliacion')
    op.drop_index(op.f('ix_vehiculo_id'), table_name='vehiculo')
    op.drop_table('vehiculo')
    op.drop_index(op.f('ix_usuario_id'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_tipo_incidente_id'), table_name='tipo_incidente')
    op.drop_table('tipo_incidente')
    op.drop_index(op.f('ix_sesion_id'), table_name='sesion')
    op.drop_table('sesion')
    op.drop_table('rol_permiso')
    op.drop_index(op.f('ix_dispositivo_usuario_id'), table_name='dispositivo_usuario')
    op.drop_table('dispositivo_usuario')
    op.drop_index(op.f('ix_rol_id'), table_name='rol')
    op.drop_table('rol')
    op.drop_index(op.f('ix_persona_id'), table_name='persona')
    op.drop_table('persona')
    op.drop_index(op.f('ix_permiso_id'), table_name='permiso')
    op.drop_table('permiso')
    op.drop_index(op.f('ix_especialidad_id'), table_name='especialidad')
    op.drop_table('especialidad')
    op.drop_index(op.f('ix_categoria_incidente_id'), table_name='categoria_incidente')
    op.drop_table('categoria_incidente')
    # ### end Alembic commands ###
