"""create tipo_servicio table and update quote_request foreign key

Revision ID: create_tipo_servicio_table
Revises: add_quote_request_fotos
Create Date: 2026-06-06 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'create_tipo_servicio_table'
down_revision: Union[str, Sequence[str], None] = 'add_quote_request_fotos'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Crear tabla tipo_servicio
    op.create_table(
        'tipo_servicio',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('nombre', sa.String(length=200), nullable=False),
        sa.Column('descripcion', sa.String(length=500), nullable=True),
        sa.UniqueConstraint('nombre')
    )
    
    # Insertar tipos de servicios de ejemplo
    op.execute("""
        INSERT INTO tipo_servicio (nombre, descripcion) VALUES
        ('Cambio de aceite', 'Cambio de aceite y filtro'),
        ('Reparación de frenos', 'Reparación o cambio de pastillas de freno'),
        ('Revisión general', 'Revisión general del vehículo'),
        ('Cambio de batería', 'Cambio de batería del vehículo'),
        ('Alineación y balanceo', 'Alineación y balanceo de ruedas')
    """)
    
    # Actualizar foreign key en quote_request
    op.execute("ALTER TABLE quote_request DROP CONSTRAINT quote_request_id_servicio_fkey")
    op.create_foreign_key(
        'quote_request_id_servicio_fkey', 'quote_request', 'tipo_servicio',
        ['id_servicio'], ['id'], ondelete='RESTRICT'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Revertir foreign key en quote_request
    op.execute("ALTER TABLE quote_request DROP CONSTRAINT quote_request_id_servicio_fkey")
    op.create_foreign_key(
        'quote_request_id_servicio_fkey', 'quote_request', 'servicio',
        ['id_servicio'], ['id'], ondelete='RESTRICT'
    )
    
    # Eliminar tabla tipo_servicio
    op.drop_table('tipo_servicio')
    # ### end Alembic commands ###
